### ISSUE TITLE
Inline bundle rendering

### ISSUE THREAD

**Issue by IlyaSemenov** [markfinger/python-webpack-manifest#4]
That would be great to allow rendering bundles inline rather than linking to them. This will speed up page loading for smaller bundles (e.g. having facebook/twitter sharing scripts combined into a single bundle).

Example:

```python
# A string containing pre-rendered script elements for the "main" entry
manifest.main.js  # '<script src="/static/path/to/file.js"><script><script ... >'

# A string containing inline pre-rendered script elements for the "main" entry
manifest.main.inline_js  # '<script>/* content of /static/path/to/file.js */<script>'
```

**Comment by markfinger** [comment]
Good idea. Would also enable inlining stylesheets easily.

A bit of bikeshedding, but `content` may be a more appropriate property name. For example, `manifest.main.content`. You'd still need to wrap the `<script>` tags around the content, but this would be a more low-level and flexible API.

I'm totally open to a PR for this.

**Comment by markfinger** [comment]
Oops, forgot to add the asset type prefix. So my suggestion would be something like `js_content` and `css content`.

Also need to consider how to handle multiple files, eg: an entry with multiple js files. Simplest approach is simply concat. 

Probably worth also exposing `js_path` and `css_path` tuples, which would be absolute paths to the files.

Exposing the content of the files would be probably be best handled through lazily evaluated `@property`  methods on the `WebpackManifestEntry` class.
