### ISSUE TITLE
Can it support code splitting? 

### ISSUE THREAD

**Issue by viperfx** [markfinger/python-webpack-manifest#6]
When bundles get large, which happen fairly easily with the inclusion of React, Redux, Component libraries etc. 

The next step to reduce the file size is code splitting based on routes. 

Here is an example: 

https://reactjs.org/docs/code-splitting.html

Does this library support it? If not, what changes need to be made to support this?

**Comment by markfinger** [comment]
Have you tried it?
 
If it doesn't, can you paste the contents of your webpack config and the generated manifest file?

**Comment by viperfx** [comment]
Thanks for getting back so quick! Yes, I did try it, but I assumed I did something wrong so I figured I will ask.

Webpack was generating the chunks and the manifest was outputting the chunks. However, when the page loaded, the chunks were loaded from the wrong path.

I will recreate the conditions and get back to you with more info.

**Comment by markfinger** [comment]
To help with debugging:

The python lib doesn't do much more than consume the generated manifest so that it can create accurate urls. If the files exist, but the urls are off, it might mean that your python config is off.

If the manifest doesn't have anything relating to the split chunks, that's probably a feature that needs to be added to the manifest plugin.

**Comment by viperfx** [comment]
Manifest:

`{"status":"done","chunks":{"null":[{"name":"0.js","path":"PATH/assets/bundles/0.js"},{"name":"0.js.map","path":"PATH/assets/bundles/0.js.map"}],"main":[{"name":"main.js","path":"PATH/assets/bundles/main.js"},{"name":"styles.css","path":"PATH/assets/bundles/styles.css"},{"name":"main.js.map","path":"PATH/assets/bundles/main.js.map"},{"name":"styles.css.map","path":"PATH/assets/bundles/styles.css.map"}],"vendor":[{"name":"vendor.js","path":"PATH/assets/bundles/vendor.js"},{"name":"vendor.js.map","path":"PATH/assets/bundles/vendor.js.map"}]}}`


Route: 
```
export default {
  path: '/reports',
  getComponent(location, cb) {
    System.import('./components/ReportView').then(module => cb(null, module.default));
  }
}
```

Webpack config

```
// var path = require('path');
var webpack = require('webpack');
var BundleTracker = require('webpack-bundle-tracker');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var CleanWebpackPlugin = require('clean-webpack-plugin')
var path = require('path');

// Not sure what flags we're setting on Prod; this will probably surfice for now
var isOSX = process.platform == 'darwin' 

let pathsToClean = [
  'assets/bundles'
]

module.exports = {
  devtool: 'cheap-module-source-map',
  entry: {
    main: ["babel-polyfill", './assets/public-facing/main.js'],
  },
  module: {
    loaders: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      loader: 'babel-loader'
    },
    {
      test: /\.less|\.css$/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: ['css-loader', 'less-loader']
      })
    },
    {
      test: /\.json$/, 
      loader:"json-loader"
    }]
  },
  resolve: {
    extensions: ['.js', '.jsx', '.json'], 
    modules: ["node_modules", "assets/public-facing"]
  },
  plugins: [
    new CleanWebpackPlugin(pathsToClean),
    new BundleTracker({filename: './webpack-stats.json'}),
    new ExtractTextPlugin("styles.css"),
    new webpack.optimize.CommonsChunkPlugin({
      name: "vendor",
      minChunks: function(module){
        if(module.resource && (/^.*\.(css|scss)$/).test(module.resource)) {
          return false;
        }
        return module.context && module.context.includes("node_modules");
      }
    }),
  ],
  output: {
    path: path.resolve('./assets/bundles/'),
    filename: '[name].js' // 
  },
  devServer: {
    contentBase: './dist'
  }
};
```

What happens on the front end:

<img width="384" alt="screen shot 2018-06-11 at 12 19 38 pm" src="https://user-images.githubusercontent.com/328257/41228864-c61e0c5a-6d71-11e8-8346-004e351fa6a5.png">

Vendor is loaded from http://localhost:8181/static/bundles/vendor.js
Main.js is still loaded
0.js is loaded from http://localhost:8181/reports/0.js

**Comment by markfinger** [comment]
I'm not too familiar with `CommonsChunkPlugin`, but maybe there's a missing prefix or filename declaration in your webpack config which is causing an attempt to load `reports/0.js` (assuming that `static/bundles/0.js` is what it should be).

TBH, this looks like the typical webpack issue, where the solution is some tiny arcane tweak to the config file. It doesn't look like either the manifest plugin or the manifest lib is at fault here.

**Comment by markfinger** [comment]
To clarify, I'm assuming that `0.js` is being loaded dynamically by webpack during the initial bootstrap. If so, the problem is very likely to be a webpack config issue.

If you're explicitly linking to the `0.js` chunk in a template or somesuch, then the url generation is probably messing up in the python lib.

**Comment by viperfx** [comment]
Okay understood. What I have realised is that the vendor.js is the main large script. The actual app chunk file is much smaller compared to vendor. These small 0.js don't make a big difference.

Do you have any techniques you have used to build the hashes for vendor and app files independently?  Meaning if node_modules do not change, don't generate new hash. (I know this is a bit webpack specific)

**Comment by markfinger** [comment]
> Do you have any techniques you have used to build the hashes for vendor and app files independently? Meaning if node_modules do not change, don't generate new hash. (I know this is a bit webpack specific)

Not off the top of my head. It's been a few years since I've dug into webpack land, and most of the systems I've built only used a single bundle.
